# -*- coding: utf-8 -*-
"""kesavarthini.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UXVdr5ajmwMioZtH2XBXoZuJWQtJtG5f
"""



#2 to calculate net price and GST amount
mobile_cost=int(input())
print("GST is 18%")
GST_amount=((mobile_cost)*(18/100))
Net_price=GST_amount+mobile_cost
print (GST_amount: 'Total GST')
print (Net_price)

#4 to calculate BMI and check health status
name=["Keerthi", "Kesa", "Varthini", "Kathir", "Sheeba", "Shiva", "Harish", "Sandra", "Sandhiya", "Imman"]
doy=[2003, 2002, 2001, 1983, 1986, 1999, 2008, 1971, 1985, 2004] 
age=[19, 20, 21, 39, 36, 23, 14, 51, 37, 18]
weight_inkg=[45, 50, 56, 80, 75, 60, 30, 78, 60, 70]
height_inmtrs=[4, 4, 5, 6, 3, 5, 5, 3, 3, 6]
bmi=[2.815, 3.125, 2.24, 2.22, 8.33, 2.4, 1.2, 8.66, 6.66, 1.94]
status=["healthy", "healthy", "unhealthy", "healthy", "healthy", "unhealthy", "healthy", "unhealthy", "healthy", "unhealthy"]
import pandas as pd
data=pd.DataFrame({'Name':name, 'Year of Birth':doy, 'Age':age, 'Weight':weight_inkg, 'Height':height_inmtrs, 'BMI':bmi, 'Status':status})
print(data)

"""# New Section"""

#program to calculate EB bill